### ISSUE TITLE
Missing `jest` dependency

### ISSUE THREAD

**Issue by DCzajkowski** [simonsmith/cypress-image-snapshot#3]
The package @simonsmith/cypress-image-snapshot@6.1.1 does not provide `jest`, even though it is a `peerDependency` of `jest-image-snapshot`. It should be included in its `peerDependencies` with the same version range: `>=20 <=29`

Warning in the console:
```
@simonsmith/cypress-image-snapshot@npm:6.1.1 [d859c] doesn't provide jest (pd104e), requested by jest-image-snapshot
```

**Comment by simonsmith** [comment]
Yes, I also noticed this warning. 

I'm tempted to ignore it because we do not actually use Jest. The function used here [is an internal function](https://github.com/americanexpress/jest-image-snapshot/blob/main/src/diff-snapshot.js#L204) that has no use of Jest

Doesn't seem correct to force users to download Jest as a dependency that is not used. Perhaps there is a way to ignore?

**Comment by DCzajkowski** [comment]
> Perhaps there is a way to ignore?

I am not aware if that's possible :/

**Comment by simonsmith** [comment]
It looks like the best option is for consumers of the library to enable the `logFilters` option

https://yarnpkg.com/configuration/yarnrc#logFilters

Could potentially add a note to the README on this

**Comment by simonsmith** [comment]
Closing this for now as not critical
